/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package organillama.llamadevelopers;

import java.awt.Image;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Colque
 */
@SuppressWarnings("serial")
public class inicio extends javax.swing.JFrame {

    private int timerun = 0;
    /**
     * Creates new form inicio
     */
    public inicio() {
        initComponents();
        
        ImageIcon imagen = new ImageIcon("src\\main\\java\\organillama\\llamadevelopers\\Imagenes\\inicio.png");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(fondoInicio.getWidth(), fondoInicio.getHeight(), Image.SCALE_DEFAULT));
        fondoInicio.setIcon(icono);
        
        ImageIcon imagenI = new ImageIcon("src\\main\\java\\organillama\\llamadevelopers\\Imagenes\\llamadevelopers.png");
        Icon iconoI = new ImageIcon(imagenI.getImage().getScaledInstance(llamadevlogo.getWidth(), llamadevlogo.getHeight(), Image.SCALE_DEFAULT));
        llamadevlogo.setIcon(iconoI);
        
        new Thread(){
            @Override
            public void run(){
                while (timerun == 0){
                    Calendar cal = new GregorianCalendar();
                    
                    int hour = cal.get(Calendar.HOUR);
                    int min = cal.get(Calendar.MINUTE);
                    int sec = cal.get(Calendar.SECOND);
                    int AM_PM = cal.get(Calendar.AM_PM);
                    
                    String day_night = "";
                    
                    if(AM_PM == 1)
                    {
                        day_night = "PM";
                    }
                    else
                    {
                        day_night = "AM";
                    }
                    
                    String time = hour + ":" + min + ":" + sec + "" + day_night;
                    Reloj.setText(time);
                }
            }
        }.start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        RELOJpnl = new javax.swing.JPanel();
        Reloj = new javax.swing.JLabel();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        organillamalbl = new javax.swing.JLabel();
        llamadevlogo = new javax.swing.JLabel();
        MinimizarBtn = new javax.swing.JPanel();
        MinimizarLbl = new javax.swing.JLabel();
        CerrarBtn = new javax.swing.JPanel();
        CerrarLbl = new javax.swing.JLabel();
        fondoInicio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RELOJpnl.setBackground(new java.awt.Color(255, 255, 255));
        RELOJpnl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        RELOJpnl.setForeground(new java.awt.Color(255, 255, 255));

        Reloj.setBackground(new java.awt.Color(255, 153, 102));
        Reloj.setFont(new java.awt.Font("alarm clock", 0, 100)); // NOI18N
        Reloj.setForeground(new java.awt.Color(0, 0, 0));
        Reloj.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Reloj.setToolTipText("");

        javax.swing.GroupLayout RELOJpnlLayout = new javax.swing.GroupLayout(RELOJpnl);
        RELOJpnl.setLayout(RELOJpnlLayout);
        RELOJpnlLayout.setHorizontalGroup(
            RELOJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RELOJpnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Reloj, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                .addContainerGap())
        );
        RELOJpnlLayout.setVerticalGroup(
            RELOJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RELOJpnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Reloj, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(RELOJpnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 550, 120));

        jCalendar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jCalendar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 550, 420));

        organillamalbl.setFont(new java.awt.Font("Forte", 0, 70)); // NOI18N
        organillamalbl.setForeground(new java.awt.Color(51, 51, 51));
        organillamalbl.setText("OrganiLlama");
        jPanel1.add(organillamalbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 400, 80));
        jPanel1.add(llamadevlogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 90, 90));

        MinimizarBtn.setBackground(new java.awt.Color(51, 153, 0));
        MinimizarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizarBtnMouseClicked(evt);
            }
        });

        MinimizarLbl.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        MinimizarLbl.setText("_");
        MinimizarLbl.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        MinimizarLbl.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout MinimizarBtnLayout = new javax.swing.GroupLayout(MinimizarBtn);
        MinimizarBtn.setLayout(MinimizarBtnLayout);
        MinimizarBtnLayout.setHorizontalGroup(
            MinimizarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MinimizarBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MinimizarLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MinimizarBtnLayout.setVerticalGroup(
            MinimizarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MinimizarBtnLayout.createSequentialGroup()
                .addComponent(MinimizarLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        jPanel1.add(MinimizarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 20, -1));

        CerrarBtn.setBackground(new java.awt.Color(255, 51, 51));
        CerrarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarBtnMouseClicked(evt);
            }
        });

        CerrarLbl.setText("X");

        javax.swing.GroupLayout CerrarBtnLayout = new javax.swing.GroupLayout(CerrarBtn);
        CerrarBtn.setLayout(CerrarBtnLayout);
        CerrarBtnLayout.setHorizontalGroup(
            CerrarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CerrarBtnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CerrarLbl)
                .addGap(14, 14, 14))
        );
        CerrarBtnLayout.setVerticalGroup(
            CerrarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CerrarBtnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CerrarLbl)
                .addGap(24, 24, 24))
        );

        jPanel1.add(CerrarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 20, 30));

        fondoInicio.setBackground(new java.awt.Color(255, 153, 102));
        fondoInicio.setForeground(new java.awt.Color(255, 102, 51));
        jPanel1.add(fondoInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CerrarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarBtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CerrarBtnMouseClicked

    private void MinimizarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarBtnMouseClicked
        setExtendedState(ICONIFIED);
    }//GEN-LAST:event_MinimizarBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CerrarBtn;
    private javax.swing.JLabel CerrarLbl;
    private javax.swing.JPanel MinimizarBtn;
    private javax.swing.JLabel MinimizarLbl;
    private javax.swing.JPanel RELOJpnl;
    private javax.swing.JLabel Reloj;
    private javax.swing.JLabel fondoInicio;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel llamadevlogo;
    private javax.swing.JLabel organillamalbl;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the timerun
     */
    public int getTimerun() {
        return timerun;
    }

    /**
     * @param timerun the timerun to set
     */
    public void setTimerun(int timerun) {
        this.timerun = timerun;
    }
}
